# Chapter 4: NumPy

NumPy is a popular library in the Python ecosystem and a critical component of the SciPy stack. So much so that NumPy is even included in Apple’s default installation of Python and in other Python-powered applications such as Blender.
It will often allow you to solve problems with less effort and time and with shorter and faster-executing code. This is due to:

- NumPy automatically propagating operations to all values in an array instead of requiring for loops
 
- A massive collection of functions for working with numerical data

- Many of NumPy’s functions are Python-wrapped C code, making them run faster

In [2]:
import numpy as np

## 4.1 NumPy Arrays

One of the main NumPy contributions is *ndarray* (n-dimensional array). This is an object similar to a list or nested lists except that mathematical operations and NumPy functions automatically propagate to each element. In turn not requiring a for loop to iterate over it. 

Because of their power and convenience, arrays are the default object type for any operation performed with NumPy and many scientific libraries that are built on NumPy (e.g., SciPy, pandas, scikit-learn, etc.).

### 4.1.1 Basic Arrays

The numpy array looks like a python list wrapped in `array()`, it is an iterable object and can be iterated over using a `for` loop. However since numpy automatically propagates through the array loops are unnecessary.

In [3]:
nums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
for value in nums:
    print (2 * value)

0
2
4
6
8
10
12
14
16
18


In [4]:
arr = np.array(nums) # Convert list to NumPy array, removing need for loop
print(arr * 2)

[ 0  2  4  6  8 10 12 14 16 18]


### 4.1.2 Type Conversion to Arrays

There are three common ways to generate a numpy array- the first is simply convert a list or yuple to an array using `np.array()` this is shown above

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 4.1.3 Array from Sequence

We can also create arrays using numpy sequence-generating functions, there are two common functions in numpy for this:
- `np.arange()`
- `np.linspace()`

The `np.arange()` function behaves similarly to the native Python `range()` function with the key difference that it outputs an array.
The arguments for `np.arange()` are similar to those of Python’s `range()` function where start is inclusive and stop is exclusive, but unlike range(), the step size for `np.arange()` does not need to be an integer value.
```python
np.arange(start, stop, step)
```

The `np.linspace()` function is related to `np.arange()` except that instead of defining the sequence based on step sixe, it bases it on how many evenly distributed points to generate in the given span of numbers. Additionally, `np.arange()` excludes the **stop** values while `np.linspace()` includes them. The difference between these two functions is somewhat subtle, and the use of one over the other often comes down to user preference or convenience.
```python
np.linspace(start, stop, number of points)
```

In [6]:
arr = np.arange(0, 10, 0.5) #start, stop, step
arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [7]:
arr = np.linspace(0, 10, 20) #start, stop, number of points
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

Two other useful functions for generating arrays are `np.zeros()` and `np.ones()`, which generate arrays populated with exclusively **zeros** and **ones**, respectively. The functions accept the shape argument as a tuple of the array dimensions in the form (rows, columns).

In [8]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

They can be used for generating arrays filled with other values, an array of zeros can be generated and then incremented by any value

In [10]:
arr = np.zeros((2, 4))
arr += 3
print(arr)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]


### 4.1.4 Arrays from Functions

The third approach is to generate arrays form a function with the use of `np.fromfunction()`, which generates an array of values using the array indices as inputs. This function requires a function as an argument.
```python
np.fromfunction(function,shape)
```

In [11]:
def prod(x,y):
    return x * y

In [12]:
#Array of the dimensions 3x3 where each element is the product of the row and column indices
np.fromfunction(prod, (3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

## 4.2 Reshaping & Merging Arrays

Modifying the dimensions of one or more arrays is a common task with numpy. This can involve changing the number of columns and rows or merging multiple arrays into a larger array. Size and shape of an array are the number of elements and dimensions, respectively. These can be determined using `size` and `shape` methods.

In [13]:
counting = np.array([[1,2,3], [4,5,6]])
counting

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
counting.size

6

In [15]:
counting.shape #(rows, columns) is the numpy convention of a two-dimensional array

(2, 3)

### 4.2.1 Reshaping Arrays

The dimensions of arrays can be modified using the `np.reshape()` method. This method maintains the number of elements and order of elements in the array but repacks them into a different number of **rows and columns**. Because the number of elements is maintained, the new array size needs to be able to contain the same number of elements as the original.

```python
np.reshape(array, dimensions)
```

In this function, `array` is the NumPy array being reshaped and `dimensions` is a tuple containing the desired number of rows and columns in that order. The original array must fit exactly into the new dimensions or else NumPy will refuse to change it. This method does not change the original array in place but rather returns a modified copy. 

In [16]:
array_1D = np.linspace(0, 9.5, 20) #Start, Stop, No. of spaces
array_1D

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [17]:
array_2D = np.reshape(array_1D, (4, 5)) #4 rows, 5 columns (has to be factors of the 20 range set in array_1D)
array_2D

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

As an alternative and preferred way to reshape an array, the `reshape()` function can be used as an array method. Start with the original array and follow it with `.reshape((rows, columns))` like below. This format is often preferred.

In [18]:
array_1D.reshape((4, 5))

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

If you need to reshape an array with only one new dimension known, place a `-1` in the other. This signals to NumPy that it should choose the second dimension to make the data fit.

In [19]:
array_1D.reshape((-1, 5)) #NumPy figures out the number of rows needed

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

In [20]:
array_1D.reshape((4, -1)) #NumPy figures out the number of rows needed

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

### 4.2.2 Flatten Arrays
Flattening an array takes a `higher-dimensional array` and squishes it into a `one-dimensional array.` To flatten out an array, the np.flatten() method is often the most convenient way.

In [21]:
array_2D.flatten() #returns a flattened copy of the array, reverse of reshape, dimension becomes 1 x 20

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

### 4.2.3 Transpose Arrays

The `np.transpose()` or `array.T` method transposes the NumPy array, effectively **flipping the rows and columns.**

The `np.transpose()` method flips the rows and columns. NumPy also provides an alias/shortcut of `array.T` to accomplish the same outcome. The latter is far more common.

In [22]:
array_2D

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

In [23]:
array_2D.T

array([[0. , 2.5, 5. , 7.5],
       [0.5, 3. , 5.5, 8. ],
       [1. , 3.5, 6. , 8.5],
       [1.5, 4. , 6.5, 9. ],
       [2. , 4.5, 7. , 9.5]])

### 4.2.4 Merge Arrays

Merging arrays can be done in multiple ways. NumPy provides convenient methods for merging arrays using `np.vstack`, `np.hstack`, and `np.dstack`, which merge arrays along the **vertical**, **horizontal**, and **depth-wise** axes.

In [24]:
a = np.arange(0, 5)
b = np.arange(5, 10)

a, b

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [25]:
np.vstack((a, b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
np.hstack((a, b))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.dstack((a, b))

array([[[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]]])

A related function is the `np.column_stack()` function that stacks the corresponding elements in column lists in a column arrangement. The outcome of the `np.column_stack()` function can also be accomplished by **transposing** the output of the `np.vstack()` function.

In [28]:
np.column_stack((a, b))

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [29]:
np.vstack((a, b)).T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

## 4.3 Indexing Arrays
Similar to lists, it is often useful to be able to index and slice NumPy arrays. Because arrays are often higher dimensional, there are some differences in indexing that provide extra convenience.

### 4.3.1 One-Dimensional Arrays
Indexing one-dimensional arrays is done in an identical fashion to lists. Simply include the index value(s) or range in square brackets behind the array name.

In [30]:
array_1D

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [31]:
array_1D[5]

np.float64(2.5)

### 4.3.2 Two-Dimensional Arrays

Two-dimensional arrays can also be indexed in a similar fashion to nested lists, but because arrays are often **multidimensional**, there is also a shortcut to make working with arrays more convenient. To access the entire second row of an array, provide the row index in square brackets behind the array name just like indexing in lists.

To access the first element in the second row, it is perfectly valid to use two adjacent square brackets just as one would use in a nested list of lists. However, to make work more convenient, these square brackets are often combined with the row and column indices separated by commas

```python
array_name[rows, columns]
```

In [32]:
array_2D

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

In [33]:
array_2D[1]

array([2.5, 3. , 3.5, 4. , 4.5])

In [34]:
array_2D[1][0]

np.float64(2.5)

In [35]:
array_2D[1, 0]

np.float64(2.5)

Ranges of values can also be accessed in arrays by using `slicing`.

In [36]:
array_2D[1, 1:]

array([3. , 3.5, 4. , 4.5])

In [37]:
array_2D[0:,3:] #From all rows, column 3 to end i.e. last two columns of all rows

array([[1.5, 2. ],
       [4. , 4.5],
       [6.5, 7. ],
       [9. , 9.5]])

As seen above, if you want to access an entire row, it is not necessary to indicate the columns. It is implicitly understood that all columns are requested. However, if you want to access the first column, something needs to be placed before the column. The easiest solution is to use a colon to explicitly indicate all rows.

In [38]:
array_2D[0] # implicitly understood all columns

array([0. , 0.5, 1. , 1.5, 2. ])

In [39]:
array_2D[0, :] # explicitly indicating all columns

array([0. , 0.5, 1. , 1.5, 2. ])

In [40]:
array_2D[:, 0]     # all rows

array([0. , 2.5, 5. , 7.5])

### 4.3.3 Advanced Indexing

In the event you have a **multidimensional array**, you can access elements in the array using multiple collections of values (i.e., NumPy arrays, lists, or tuples) where each collection indicates the location along a different dimension. 

Another feature of indexing NumPy arrays is that the returned array will have the same dimensions as the array containing the indices. In the following example, we have two index arrays where `i_flat` is a 1 x 4 array while `i_square` is a 2 x 2 array resulting in 1 x 4 and 2 x 2 arrays, respectively.

In [41]:
threes = np.arange(3, 30, 3) #start, stop, step - this gives 3 times table to 27

i_flat = np.array([0, 3, 1, 5])
i_square = np.array([[0, 3],
                     [1, 5]])

In [42]:
threes[i_flat]

array([ 3, 12,  6, 18])

In [43]:
threes[i_square]

array([[ 3, 12],
       [ 6, 18]])

The latter result can also be accomplished by indexing using a flat (i.e., one-dimensional) array followed by reshaping it to the desired dimensions, as demonstrated below.

In [44]:
i = np.array([-1, 3, 1, 5])

threes[i].reshape((2, 2))

array([[27, 12],
       [ 6, 18]])

### 4.3.4 Masking

Elements in a NumPy array can also be selected using a `boolean` array through a process known as masking. 

The masking array is a boolean array filled with either `1` and `0` or `True` and `False` and has the same dimensions as the original array. Any element in the original array that has a `1` or `True` in the corresponding position of the masking array is returned.

In [45]:
orig_array = np.array([[5, 7, 1],
                       [3, 4, 2],
                       [0, 9, 8]])

mask = np.array([[0, 1, 0],
                 [1, 1, 1],
                 [1, 0, 1]], dtype=bool)

In [46]:
orig_array[mask]

array([7, 3, 4, 2, 0, 8])

It’s important to note that if you use `1` and `0` in the masking array, it is required that you include `dtype=bool` or else NumPy will treat the 1 and 0 as `indices` instead of `booleans` and attempt indexing.

In [47]:
mask = np.array([[0, 1, 0],
                 [1, 1, 1],
                 [1, 0, 1]])

orig_array[mask]

array([[[5, 7, 1],
        [3, 4, 2],
        [5, 7, 1]],

       [[3, 4, 2],
        [3, 4, 2],
        [3, 4, 2]],

       [[3, 4, 2],
        [5, 7, 1],
        [3, 4, 2]]])

The true power of **masking** is when the masking array is generated through `boolean` logic such as `>`, `<=`, or `==`. This enables the user to select elements of an array through conditions as demonstrated below where we select all elements of the `orig_array` that are greater than 5.

In [48]:
cond = orig_array > 5
cond

array([[False,  True, False],
       [False, False, False],
       [False,  True,  True]])

In [49]:
orig_array[cond]

array([7, 9, 8])

In [50]:
# We can also include the condition directly in the square brackets to save a step, as shown below.
orig_array[orig_array > 5]

array([7, 9, 8])

## 4.4 Vectorization & Broadcasting

One of the major advantages of NumPy arrays over lists is that operations automatically *vectorize* across the arrays. That is, mathematical operations propagate through the **array(s)** instead of requiring for loops. This both speeds up the calculations and makes the code easier to read and write.

### 4.4.1 NumPy Functions
Let’s take the square root of numbers using NumPy’s `np.sqrt()` function. The square root is taken of each element automatically.

In [51]:
squares = np.array([1, 4, 9, 16, 25])
np.sqrt(squares)

array([1., 2., 3., 4., 5.])

Performing this operation requires NumPy’s `sqrt()` function. If this is attempted with the `math` module’s `sqrt()` function, an error is returned because this function cannot take the square root of a multi-element object without loops.

In [52]:
import math
math.sqrt(squares)

TypeError: only 0-dimensional arrays can be converted to Python scalars

To get the same result you would need the for loop, which works however in comparison is clunky and requires the math package.

In [ ]:
squares_for = []

for x in squares:
    squares_for.append(math.sqrt(x))

squares_for

[1.0, 2.0, 3.0, 4.0, 5.0]

### 4.4.2 Scalars & Arrays

When performing mathematical operations between a **scalar** and an **array**, the same operation is performed across each element of the array, returning an array of the same dimension as the starting array. Below, an array is multiplied by the scalar 3, which results in every element in the array being multiplied by this value.

The same outcome arises when performing a similar operation between a 1 x 1 array and a larger array (2 x 1 in example but this scales).



In [ ]:
3 * np.array([[5, 6], 
              [7, 8]])

array([[15, 18],
       [21, 24]])

In [ ]:
np.array([2]) + np.array([10, 20])

array([12, 22])

### 4.4.3 Arrays of the Same Dimensions

If a mathematical operation is performed between two arrays of the same dimensions, then the mathematical operation is performed between corresponding elements in the two arrays. For example, if a pair of 2 x 2 arrays are added to one another, then the corresponding elements are added to one another. This means that the top-left elements are added together and so on.

In [ ]:
a = np.array([[1, 2], 
              [3, 4]]) 
b = np.array([[5, 6], 
              [7, 8]]) 

a + b

array([[ 6,  8],
       [10, 12]])

### 4.4.4 Arrays of Different Dimensions

Broadcasting is another form of vectorisation that is a series of rules for dealing with mathematical operations between two arrays of different dimensions. In broadcasting, one of the dimensions of the two arrays must be either identical or one-dimensional; otherwise, nothing happens except an error message. 

To deal with the different dimensions, NumPy clones the array with fewer dimensions out so that it has the same dimensions as the other array. It should be noted that NumPy does not really clone out the array in the background; its behaviour acts as if it does. It is a convenient way of thinking about the behaviour and results. For example, below is the addition between a 2 x 2 and a 1 x 2 array.

To make the two arrays the same size, the smaller array is cloned along the smaller dimension until the two arrays are the same size, we are then left with simple corresponding element-by-corresponding-element mathematical operations.

One of either columns or rows have to match; more precisely, the trailing dimensions must match, or the smaller one must be 1 so it can broadcast.



In [ ]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([2, 5])
a + b

array([[3, 7],
       [5, 9]])

If we attempt to perform a mathematical operation between two arrays with different dimensions and none of the arrays have a dimension of one where the two arrays are different, an error is raised, and no operation is performed.

In [ ]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[1, 1, 1], 
              [2, 2, 2], 
              [3, 3, 3]]) 
a + b

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

### 4.4.5 Vectorizing Python Functions

Standard Python functions are often designed to perform a calculation a single time and output Python objects and not NumPy arrays. As an example, the following function calculates the rate of a first-order reaction given the rate constant (`k`) and concentration of reactant (`conc`).

In [ ]:
def rate(k, conc):
    return k * conc

In [ ]:
rate(1.2, 0.80)

0.96

What happens if we attempt the above calculation using a list of concentration values?

We get an error because Python cannot multiply a list by a value the way NumPy can. However, the above function can be converted to a NumPy function using `np.vectorize()`, which will allow the function to perform the calculation on a series of values and returns a NumPy array.

In [ ]:
concs = [0.1, 0.5, 1.0, 1.5, 2.0]
rate(1.2, concs)

TypeError: can't multiply sequence by non-int of type 'float'

In [ ]:
vrate = np.vectorize(rate)
vrate(1.2, concs)

array([0.12, 0.6 , 1.2 , 1.8 , 2.4 ])

## 4.5 Array Methods

The functions above are NumPy methods specifically for working with NumPy arrays. If an array is fed to many non-NumPy functions, an error will result because they cannot handle multi-element objects or arrays specifically. Interestingly, if a float or integer is fed into a NumPy method, it will still work. As an example, the integer 4 can be fed into the `np.sqrt()` function as well as an array of values.

In [ ]:
np.sqrt(4)

np.float64(2.0)

In [ ]:
np.sqrt(np.array([1, 4, 9]))

array([1., 2., 3.])

NumPy contains an extensive listing of methods for working with arrays below are tables of some common and useful methods. 

> It is worth browsing and being aware of them; many are worth committing to memory. If you ever find yourself needing to manipulate an array in some complex fashion, it is worth doing a quick internet search and including “NumPy” in your search. You will likely either find additional NumPy methods that will help or advice on how others solved a similar problem.

### Table 1 - Common Methods for generating Arrays.
| Method           | Description                                                     |
|------------------|-----------------------------------------------------------------|
| `np.array()`     | Generates an array from another object                          |
| `np.arange()`    | Creates an array from [start, stop) with a given step size      |
| `np.linspace()`  | Creates an array from [start, stop] with a given number of steps|
| `np.empty()`     | Creates an “empty” array (actually filled with garbage values)  |
| `np.zeros()`     | Generates an array of given dimensions filled with zeros        |
| `np.ones()`      | Generates an array of given dimensions filled with ones         |
| `np.fromfunction()` | Generates an array using a Python function                  |
| `np.genfromtxt()`   | Loads text file data into an array                          |
| `np.loadtxt()`      | Loads text file data into an array (cannot handle missing data) |

### Table 2 - Array Attribute Methods.
| Method            | Description                                      |
|-------------------|--------------------------------------------------|
| `np.shape(array)` | Returns the dimensions of an array               |
| `np.ndim(array)`  | Returns the number of dimensions                 |
| `np.size(array)`  | Returns the number of elements in an array       |


### Table 3 - Array Modification Methods.
| Method                 | Description                                                                       |
|------------------------|-----------------------------------------------------------------------------------|
| `np.flatten()`         | Flattens an array in place                                                        |
| `np.ravel()`           | Returns a flattened view without modifying the original                           |
| `np.reshape()`         | Reshapes an array in place                                                        |
| `np.resize()`          | Returns a resized view without modifying the original                             |
| `np.transpose()`       | Returns a transposed view of the array                                            |
| `np.vstack()`          | Vertically stacks arrays into a new array                                         |
| `np.hstack()`          | Horizontally stacks arrays into a new array                                       |
| `np.dstack()`          | Depth‑wise stacks arrays into a new array                                         |
| `np.vsplit()`          | Splits an array vertically                                                        |
| `np.hsplit()`          | Splits an array horizontally                                                      |
| `np.dsplit()`          | Splits an array depth‑wise                                                        |
| `np.meshgrid()`        | Creates a meshgrid                                                                |
| `np.sort()`            | Sorts elements in an array (defaults along last axis)                             |
| `np.argsort()`         | Returns index values of the sorted array                                          |
| `np.fill(x)`           | Sets all values in an array to `x`                                                |
| `np.roll()`            | Rolls the array along an axis; elements falling off one end appear at the other   |
| `np.floor()`           | Returns the floor (rounds down) of all elements                                   |
| `np.round(x, decimals=y)` | Rounds numbers in array `x` to `y` decimals using Banker’s rounding           |

### Table 4 - Array Measurement and Statistics Methods
| Method              | Description                                                                                   |
|---------------------|-----------------------------------------------------------------------------------------------|
| `np.min()`          | Returns the minimum value in the array                                                        |
| `np.max()`          | Returns the maximum value in the array                                                        |
| `np.minimum()`      | Returns element‑wise minimum values between two arrays of the same dimensions                 |
| `np.maximum()`      | Returns element‑wise maximum values between two arrays of the same dimensions                 |
| `np.argmin()`       | Returns the index of the minimum value                                                        |
| `np.argmax()`       | Returns the index of the maximum value                                                        |
| `np.argrelmax()`    | Returns the index of the local maximum                                                        |
| `np.fmin()`         | Returns the element‑by‑element minimum between two arrays of the same size                    |
| `np.fmax()`         | Returns the element‑by‑element maximum between two arrays of the same size                    |
| `np.percentile()`   | Returns the specified percentile                                                              |
| `np.mean()`         | Returns the mean (average)                                                                    |
| `np.median()`       | Returns the median                                                                            |
| `np.std()`          | Returns the standard deviation (use `ddof=1` to match Excel)                                  |
| `np.histogram()`    | Returns counts and bin edges for a histogram                                                  |
| `np.cumprod()`      | Returns the cumulative product                                                                |
| `np.cumsum()`       | Returns the cumulative sum                                                                    |
| `np.sum()`          | Returns the sum of all elements                                                               |
| `np.prod()`         | Returns the product of all elements                                                           |
| `np.ptp()`          | Returns the peak‑to‑peak range (max − min)                                                    |
| `np.unique()`       | Returns sorted unique elements; set `return_counts=True` to also get frequencies              |
| `np.unique_counts()`| Returns unique elements and a second array of their frequencies                               |


> NumPy’s np.std() uses degrees of freedom = 0 by default.
> Excel and some other software use ddof = 1, so include:
> ```python 
> np.std(array, ddof=1) 
```



### 4.6 Missing Data
Real datasets frequently contain gaps or missing values, so it is important to be able to deal with missing data. When importing data into NumPy, there are two commonly employed functions, `np.genfromtxt()` and `np.loadtxt()`. Though these are largely analogous functions in terms of capabilities, there is a key difference in that `np.genfromtxt()` can handle missing data while `np.loadtxt()` cannot. This means if your dataset may contain gaps, you should use `np.genfromtxt()`.

In the event the data file contains a gap, the `np.genfromtxt()` function will place a `NAN` in that location by default. The `NAN` stands for **“not a number”** and is simply a placeholder. 

Some data files use placeholder values instead of no value at all. These placeholders are often `-1`, `0`, `999`, or some physically meaningless or improbable value. If you have alternative values you want in the missing data location, you can specify this using the `filling_values=' argument.

### Table - Statistics Methods Dealing with NaNs

| Function           | Description        |
|--------------------|--------------------|
| `np.nanstd()`      | Standard deviation |
| `np.nanmean()`     | Mean               |
| `np.nanvar()`      | Variance           |
| `np.nanmedian()`   | Median             |
| `np.nanpercentile()` | Qth percentile   |
| `np.nanquantile()` | Qth quantile       |


## 4.7 Random Number Generation
Stochastic simulations, are a common tool in the sciences and rely on a series of random numbers, so it is worth addressing their generation using NumPy. Depending upon the requirements of the simulation, random numbers may be a series of `floats` or `integers`, and they may be generated from various ranges of values. 

The numbers may also be generated as a uniform distribution where all values are equally likely or a biased distribution where some values are more probable than others. Below are random number functions from the NumPy `random` module useful in generating random number distributions to suit the needs of your simulations.

### 4.7.1 Uniform Distribution
The simplest distribution is the uniform distribution of random numbers where every number in the range has an equal probability of occurring. The distribution may not always appear as even with small sample sizes due to the random nature of the number generation, but as a larger population of samples is generated, the relative distribution will appear more even.

Starting in version 1.18, NumPy’s preferred method for producing random values is through a Generator called using the `rng = np.random.default_rng()` function. Once a generator has been created, it can be used to generate the necessary random values. NumPy has multiple methods available for generating evenly-distributed random numbers including the following two functions where n is the number of random values to be generated. The `rng.random(n)` function generates n random floats from the range [0,1). The `rng.integers(low, high=, size=n)` function generates random integers in the range [low, high) and can generate multiple values using the size argument.

In [54]:
rng = np.random.default_rng()
rng.random(5)

array([0.39531191, 0.15116671, 0.38457878, 0.39183552, 0.5080235 ])

In [55]:
rng.integers(0, high=10, size=10)

array([3, 1, 9, 0, 5, 5, 5, 8, 5, 8])

### 4.7.2 Binomial Distribution
A binomial distribution results when values are generated from two possible outcomes. This is useful for applications such as deciding if a simulated molecule reacts or whether a polymer chain terminates or propagates. The two outcomes are represented by a `0` or `1` with the probability, `p`, of a `1` being generated. Binomial distributions are generated by the NumPy random module using the `rng.binomial()` function call.
```python
rng = np.random.default_rng()

rng.binomial(t, p, size=n)
```
The `t` argument is the number of trials, while the `size=` argument is the number of generated values. For example, if `t = 2`, two binomial values are generated, and the sum is returned, which may be `0`, `1`, or `2`. Basic probability predicts that these sums will occur in a **1:2:1** ratio, respectively. If `t` is increased to 10, a shape more closely representing a bell curve is obtained. A **Bernoulli distribution** is the specific instance of a binomial distribution where `t = 1`.

In [56]:
rng = np.random.default_rng()
rng.binomial(2, 0.5, size=10)

array([0, 0, 1, 1, 2, 0, 2, 1, 2, 1])

### 4.7.3 Poisson Distribution
A Poisson distribution is a probability distribution of how likely it is for independent events to occur in a given interval (time or space) with a known average frequency (`lam`). Each sample in a Poisson distribution is a count of how many events have occurred in the time interval, so they are always integers. NumPy can generate integers in a Poisson distribution using the `rng.poisson()` function, which accepts two arguments.
```python
rng.poisson(lam=1.0, size=n)
```
The first argument, (`lam`), is the statistical mean for the values generated, and the second argument, `size`, is the requested number of values. For example, a Geiger counter can be simulated detecting background radiation in a location that is known to have an average of 3.6 radiation counts per second with the following function call.

In [57]:
rng.poisson(lam=3.6, size=30)

array([2, 5, 3, 6, 1, 0, 3, 5, 2, 2, 5, 4, 7, 5, 4, 2, 3, 2, 3, 5, 4, 2,
       3, 6, 2, 7, 5, 6, 5, 2])

The returned array of values is the total radiation detections for each second for thirty seconds, the larger sample sizes are statistically more likely to generate results closer to the target value.  In addition, the larger number of values results in a classic Poisson distribution curve which appears something like a bell curve with more tapering on the high end.

Alternative distributions of random numbers can be generated by manipulating the output of the above functions. For example, random numbers in a [-1, 1) distribution, which is useful in a 2D diffusion simulation, can be generated by subtracting 0.5 from values in the range [0, 1) and multiplying by two.

In [58]:
rand_float = 2 * (rng.random(10) - 0.5)
rand_float

array([-0.62519677, -0.86157544,  0.01905951,  0.74957937, -0.77944518,
       -0.34878892,  0.56696803,  0.15970584,  0.56339303, -0.9992335 ])

## 4.7.4 Other Functions

The random module in NumPy also includes a large variety of other random number and sequence generators. This includes `rng.normal()`, which generates values centered around zero in a normal distribution. The `rng.choice()` function selects a random value from a provided array of values, while the `rng.shuffle()` function randomizes the order of values for a given array. Other random distribution functions can be found on the SciPy website (see Further Reading).

A summary of common NumPy random functions is shown in **Table 6**.

### Table — Summary of Common NumPy `np.random` Functions

| Function       | Description |
|----------------|-------------|
| `rng.random()`   | Generates random floats in the range [0,1) in an even distribution |
| `rng.integers()` | Generates random integers from a given range in an even distribution |
| `rng.normal()`   | Generates random floats in a normal distribution centered around zero |
| `rng.binomial()` | Generates random integers in a binomial distribution; takes a probability *p* and size arguments |
| `rng.poisson()`  | Generates random floats in a Poisson distribution